### ISSUE TITLE
"Has to inherit from MonoBehaviour so we can use Instantiate()" - wrong

### ISSUE THREAD

**Issue by andypoly** [Habrador/Unity-Programming-Patterns#9]
The code comment is wrong. You can make a reusable GameObject pool without monobehaviour because you can call Object.Instantiate - you just have to pass a prefab GameObject to it on creation. But that could be in a parent class or a pool manager monobehaviour.

**Comment by Habrador** [comment]
Thank you for your feedback - Ive added it as a comment!
